### ISSUE TITLE
500 Internal Server Error already use .htaccess

### ISSUE THREAD

**Issue by chobitsos** [mhaas/fbwlan#16]
.htaccess info

```
RewriteEngine On
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
#RewriteCond %{REQUEST_URI} !=/index.php
RewriteRule ^(.*)$ index.php [QSA,L]

```

Connect to Facebook is working
already Facebook login successful!

but When you "click Check in to Message"
then

```
500 Internal Server Error

Use of undefined constant place - assumed 'place' (8)

#0 /home/wwwroot/router.xxxx.com/handlers/fb_handlers.php(201): flight\Engine->handleError(8, 'Use of undefine...', '/home/wwwroot/r...', 201, Array)
#1 /home/wwwroot/router.xxxx.com/include/flight/flight/core/Dispatcher.php(160): handle_checkin()
#2 /home/wwwroot/router.xxxx.com/include/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction('handle_checkin', Array)
#3 /home/wwwroot/router.xxxx.com/include/flight/flight/Engine.php(313): flight\core\Dispatcher::execute('handle_checkin', Array)
#4 /home/wwwroot/router.xxxx.com/include/flight/flight/core/Dispatcher.php(191): flight\Engine->_start()
#5 /home/wwwroot/router.xxxx.com/include/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#6 /home/wwwroot/router.xxxx.com/include/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#7 /home/wwwroot/router.xxxx.com/include/flight/flight/Engine.php(64): flight\core\Dispatcher->run('start', Array)
#8 /home/wwwroot/router.xxxx.com/include/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#9 /home/wwwroot/router.xxxx.com/include/flight/flight/core/Dispatcher.php(191): flight\Engine->start()
#10 /home/wwwroot/router.xxxx.com/include/flight/flight/Flight.php(76): flight\core\Dispatcher::invokeMethod(Array, Array)
#11 /home/wwwroot/router.xxxx.com/index.php(85): Flight::__callStatic('start', Array)
#12 /home/wwwroot/router.xxxx.com/index.php(85): Flight::start()
#13 {main}
```

Can not Check In!!
what's going on?

server：PHP/5.4.41 Apache2.4
the facebok api publish_actions i test is working!

**Comment by chobitsos** [comment]
the facebok api publish_actions i test is working!

**Comment by mhaas** [comment]
Try a git pull.
